# HTCondor submit file - model.sub

universe = vanilla
executable = /home/ubuntu/Project7008/code/Model/model.sh

arguments = "$(Process)"

output     = /home/ubuntu/Project7008/code/out/out_Model_$(Process).out
error      = /home/ubuntu/Project7008/code/err/err_Model_$(Process).err
log        = /home/ubuntu/Project7008/code/log/log_Model_$(Process).log

request_cpus = 2
request_memory = 2048
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 1