# HTCondor submit file - post-processing.sub

universe = vanilla
executable = /home/ubuntu/Project7008/code/post-processing/post-processing.sh

arguments = "$(Process)"

output     = /home/ubuntu/Project7008/code/out/out_postprocess_$(Process).out
error      = /home/ubuntu/Project7008/code/err/err_postprocess_$(Process).err
log        = /home/ubuntu/Project7008/code/log/log_postprocess_$(Process).log

request_cpus = 2
request_memory = 2048
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 2