
# HTCondor submit file - pre-processing.sub

universe = vanilla
executable = /home/ubuntu/Project7008/code/pre-processing/pre-processing.sh

arguments = "$(Process)"

output     = /home/ubuntu/Project7008/code/out/out_preprocess_$(Process).out
error      = /home/ubuntu/Project7008/code/err/err_preprocess_$(Process).err
log        = /home/ubuntu/Project7008/code/log/log_preprocess_$(Process).log

request_cpus = 1
request_memory = 2048
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 8

