# HTCondor submit file - EDA_test.sub

universe = vanilla
executable = /home/ubuntu/Project7008/code/EDA/EDA_test/EDA_test.sh

arguments = "$(Process)"

output     = /home/ubuntu/Project7008/code/out/out_EDA_test_$(Process).out
error      = /home/ubuntu/Project7008/code/err/err_EDA_test_$(Process).err
log        = /home/ubuntu/Project7008/code/log/log_EDA_test_$(Process).log

request_cpus = 2
request_memory = 2048
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 1